# Generated by Django 2.0.1 on 2019-04-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiledet', '0018_auto_20180330_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='legit_doctor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
