# Generated by Django 2.0.1 on 2019-04-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiledet', '0019_usermodel_legit_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='auth',
            field=models.TextField(),
        ),
    ]
